### ISSUE TITLE
Twig error on feeds list after Craft 2 migration that used a custom data type feed

### ISSUE THREAD

**Issue by jamesmacwhite** [verbb/feed-me#504]
### Description

Coming from a Craft 2 migration which had a custom data type feed under Feed Me 2.x, the feeds list doesn't load because `feed.dataType.name` returns null. This is because the feedType column value isn't valid under Craft 3.

```
Twig\Error\RuntimeError: Impossible to access an attribute ("name") on a null variable. in /app/vendor/verbb/feed-me/src/templates/feeds/index.html:48
Stack trace:
#0 /app/vendor/craftcms/cms/src/helpers/Template.php(79): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig\Source), NULL, 'name', Array, 'any', false, false)
#1 /app/storage/runtime/compiled_templates/cb/cbd0f5ce143d45c1bb2c904e8ce9dfc3ee5eb4ab863873f6cfb929fab27a7c0e.php(183): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), NULL, 'name', Array)
#2 /app/vendor/twig/twig/src/Template.php(184): __TwigTemplate_c5e2167aaca94b381e18da179bc21153cc1242f5db78ec66ab543ef27b18e1fe->block_blockContent(Array, Array)
#3 /app/storage/runtime/compiled_templates/db/db6bb5d31234e4837d3d9dea420cee06ba39f56f2b09d370ae15ef81a77bd7ba.php(58): Twig\Template->displayBlock('blockContent', Array, Array)
#4 /app/vendor/twig/twig/src/Template.php(379): __TwigTemplate_c31ac2f41357e0c5138d5d16773b608c578cb54207af4e9cac35ed379be14a46->doDisplay(Array, Array)
#5 /app/vendor/craftcms/cms/src/web/twig/Template.php(52): Twig\Template->displayWithErrorHandling(Array, Array)
#6 /app/vendor/twig/twig/src/Template.php(356): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#7 /app/vendor/craftcms/cms/src/web/twig/Template.php(34): Twig\Template->display(Array, Array)
#8 /app/storage/runtime/compiled_templates/cb/cbd0f5ce143d45c1bb2c904e8ce9dfc3ee5eb4ab863873f6cfb929fab27a7c0e.php(64): craft\web\twig\Template->display(Array, Array)
#9 /app/vendor/twig/twig/src/Template.php(379): __TwigTemplate_c5e2167aaca94b381e18da179bc21153cc1242f5db78ec66ab543ef27b18e1fe->doDisplay(Array, Array)
#10 /app/vendor/craftcms/cms/src/web/twig/Template.php(52): Twig\Template->displayWithErrorHandling(Array, Array)
#11 /app/vendor/twig/twig/src/Template.php(356): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#12 /app/vendor/craftcms/cms/src/web/twig/Template.php(34): Twig\Template->display(Array, Array)
#13 /app/vendor/twig/twig/src/Template.php(364): craft\web\twig\Template->display(Array)
#14 /app/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#15 /app/vendor/twig/twig/src/Environment.php(319): Twig\TemplateWrapper->render(Array)
#16 /app/vendor/craftcms/cms/src/web/View.php(343): Twig\Environment->render('feed-me/feeds/i...', Array)
#17 /app/vendor/craftcms/cms/src/web/View.php(393): craft\web\View->renderTemplate('feed-me/feeds/i...', Array)
#18 /app/vendor/craftcms/cms/src/web/Controller.php(161): craft\web\View->renderPageTemplate('feed-me/feeds/i...', Array)
#19 /app/vendor/verbb/feed-me/src/controllers/FeedsController.php(30): craft\web\Controller->renderTemplate('feed-me/feeds/i...', Array)
#20 [internal function]: verbb\feedme\controllers\FeedsController->actionFeedsIndex()
#21 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#22 /app/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#23 /app/vendor/craftcms/cms/src/web/Controller.php(109): yii\base\Controller->runAction('feeds-index', Array)
#24 /app/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('feeds-index', Array)
#25 /app/vendor/craftcms/cms/src/web/Application.php(297): yii\base\Module->runAction('feed-me/feeds/f...', Array)
#26 /app/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('feed-me/feeds/f...', Array)
#27 /app/vendor/craftcms/cms/src/web/Application.php(286): yii\web\Application->handleRequest(Object(craft\web\Request))
#28 /app/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#29 /app/web/index.php(21): yii\base\Application->run()
#30 {main}
```

https://github.com/verbb/feed-me/blob/craft-3/src/templates/feeds/index.html#L48

Because the custom data type feed stuff is a little different in Feed Me 3.x, I don't know if it's worth being a bit more defensive on this scenario, perhaps on the Twig side falling back to an 'Unknown' value or something similar?

To workaround this, you can update the feedType column to something that is valid. I found that implementing my custom data type feed in Craft 3 the feedType column value isn't exactly the same due the namespace and different naming schemes, so it will error until I manually edit the DB table. If at least the Twig template can load, the feed can be updated after a migration.

### Steps to reproduce

1. Have a Craft 2 custom data type feed setup in Feed Me 2.x
2. Perform a DB migration to Craft 3.
3. Attempt to access the feeds list in Feed Me through CP
4. Twig error due to null variable

### Additional info

- Plugin version: 3.1.16
- Craft version: 3.1.20.1

**Comment by engram-design** [comment]
Added some slight handling for this in [3.1.17](https://github.com/verbb/feed-me/releases/tag/3.1.17).
